---
- name: Enable intranet services
  hosts: apache
  become: true
  tasks:

    - name: latest version of apache2 and firewalld installed
      apt:
        name:
          - apache2
          - firewalld
        state: latest

    - name: test html page is installed
      copy:
        content: "Welcome to the example.com intranet!\n"
        dest:  /var/www/html/index.html

    - name: Firewall enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: Allow http service across firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: apache server enabled and running
      service:
        name: apache2
        enabled: true
        state: started

- name: test the URL functioning 
  hosts: apache
  become: true
  tasks:
    - name: connect to intranet web server
      uri:
        url: http://16.170.247.44
        return_content: yes
        status_code: 200
      register: status_output

    - name: Display the web status output
      debug:
        msg: "{{status_output.content}}"

