- name: PLAY1 - Install Apache on remote servers
  hosts: production # Production group in inventory file
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: run apt update
      apt:
        update_cache: true
    - name: install apache on ubuntu
      apt:
        name: apache2
        state: present



