- name: Play1 - Enable Internet services
  hosts: development
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Ensure firewalld, httpd, mariadbserver, php, and php-mysqlnd packages are present
      apt:
        name:
          - firewalld
          - apache2
        state: latest
    - name: Ensure orrect index.html file is in place
      copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html
        mode: 0644
    - name: Ensure the service firewalld is running
      service:
        name: firewalld
        enabled: true
        state: started
    - name: Ensure the service apache2 and mariadb running
      service:
        name: apache2
        state: started
        enabled: true

    - name: Firewall permits access to httpd service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
- name: Play 2 - Test access to web server
  hosts: localhost
  become: false
  tasks:
    - name: Connect to intranet web server
      ansible.builtin.uri:
        url: http://172.31.15.4
        return_content: yes
        status_code: 200

        




