---
- name: Install and start Apache HTTPD & mysql presence
  hosts: production
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: run apt update
      apt: 
        update_cache: true
    - name: install mysql server
      apt:
        name: apache2
        state: present
    - name: correct index.html should be present
      ansible.builtin.copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
    - name: Ensure httpd service is started
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

- name: Play2 - install mysql server on ubuntu"
  hosts: testing
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: run apt update
      apt:
        update_cache: true
    - name: install mysql server
      apt:
        name: mysql-server
        state: present
    - name: restart mysql server
      systemd:
        name: mysql
        state: started
        enabled: true






